<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NewAlbumsDiscovery.Domain\NewAlbumsDiscovery.Domain.csproj" />
  </ItemGroup>

</Project>
