// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewAlbumsDiscovery.Infrastructure.Sqlite;

#nullable disable

namespace NewAlbumsDiscovery.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260814151139_AddDiscoveredAlbums")]
    partial class AddDiscoveredAlbums
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("NewAlbumsDiscovery.Domain.AIDiscovery.DiscoveredAlbum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlbumName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DiscoveredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReferenceBucketId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceBucketId");

                    b.ToTable("DiscoveredAlbums", (string)null);
                });

            modelBuilder.Entity("NewAlbumsDiscovery.Domain.MusicAggregator.AggregatedBucket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BucketName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BucketType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<int>("TrackCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AggregatedBuckets", (string)null);
                });

            modelBuilder.Entity("NewAlbumsDiscovery.Domain.AIDiscovery.DiscoveredAlbum", b =>
                {
                    b.HasOne("NewAlbumsDiscovery.Domain.MusicAggregator.AggregatedBucket", null)
                        .WithMany()
                        .HasForeignKey("ReferenceBucketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
